insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (1, 235, 1, 'The Oblong Box', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'velit vivamus vel', 5, 10, 38.099215, 23.705891, '2712', 'Dorton', '073', '2017-05-13 12:08:43', 20.93, 7);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (2, 240, 4, 'Where Is the Friend''s Home? (Where Is My Friend''s House?) (Khane-ye doust kodjast?)', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien', 7, 9, 38.031168, 23.618427, '4620-091', 'Muir', '4', '2017-12-18 09:55:04', 20.19, 90);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (3, 215, 6, 'Year My Voice Broke, The', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.

In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', 7, 10, 38.041534, 23.67693, '95130', 'Comanche', '3', '2017-09-29 12:32:55', 8.54, 28);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (4, 105, 2, 'Worthless, The (Arvottomat)', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', 9, 12, 37.987084, 23.706768, '57013', 'Rockefeller', '76430', '2018-02-04 05:10:56', 18.85, 20);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (5, 35, 3, 'Going the Distance', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae', 3, 9, 38.085314, 23.800583, '57013', 'Holmberg', '83', '2017-11-11 08:13:41', 21.61, 86);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (6, 115, 5, 'When Night Is Falling', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 7, 10, 37.969163, 23.727098, '2430', 'Bayside', '508', '2017-04-08 02:56:42', 7.33, 99);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (7, 20, 2, 'Warriors of Virtue', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'parturient montes nascetur', 5, 10, 38.059565, 23.835016, '57013', 'Hooker', '32', '2018-02-08 03:03:00', 11.24, 23);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (8, 245, 5, 'World According to Garp, The', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'nisl aenean lectus pellentesque eget nunc donec', 9, 15, 37.994542, 23.63837, '57013', 'Clove', '8696', '2017-12-17 23:57:56', 17.21, 115);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (9, 140, 4, 'Lady and the Tramp', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'quis lectus suspendisse potenti', 4, 11, 38.02439, 23.824757, '4605-169', 'Sheridan', '62640', '2017-10-18 19:30:51', 23.08, 120);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (10, 165, 4, 'Gorgeous Hussy, The', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', 3, 14, 38.006512, 23.622518, '9408', 'Sunbrook', '5', '2017-03-18 21:49:29', 9.07, 105);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (11, 60, 5, 'Hideous Kinky', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique', 8, 9, 37.948434, 23.653583, '57013', 'Bluejay', '97086', '2017-08-08 09:51:11', 13.7, 116);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (12, 245, 5, 'Garage Sale Mystery', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'odio curabitur convallis duis consequat dui nec nisi volutpat', 3, 11, 37.931238, 23.678344, '57013', 'Buell', '91', '2017-09-17 11:15:29', 20.67, 3);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (13, 135, 4, 'House of Frankenstein', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in', 7, 10, 38.011582, 23.711215, '57013', 'Alpine', '49264', '2017-02-26 05:42:41', 12.48, 38);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (14, 190, 2, 'Bang', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet', 9, 11, 37.968532, 23.68171, '5101', 'Annamark', '9584', '2017-02-24 06:38:41', 14.64, 37);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (15, 215, 3, 'Many Adventures of Winnie the Pooh, The', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'praesent lectus vestibulum quam sapien varius ut blandit non interdum', 5, 9, 37.969143, 23.644038, '364 71', 'Hansons', '68', '2017-08-01 13:24:12', 11.33, 34);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (16, 145, 2, 'Working Class Goes to Heaven, The (a.k.a. Lulu the Tool) (La classe operaia va in paradiso)', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'consequat ut nulla sed accumsan felis ut at dolor', 8, 13, 38.017862, 23.766055, '57013', 'Monica', '9772', '2017-07-26 19:05:37', 6.09, 73);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (17, 60, 5, 'Cannonball Run II', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue', 9, 13, 37.977816, 23.791059, '57013', 'Forster', '423', '2017-04-16 09:45:10', 18.7, 57);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (18, 165, 4, 'Hard Ticket to Hawaii', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci', 3, 11, 37.93943, 23.772336, '57013', 'Arizona', '40643', '2017-09-08 12:58:43', 21.11, 38);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (19, 225, 1, 'Martin Lawrence Live: Runteldat', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar', 8, 11, 37.956533, 23.825764, '10009', 'Sutteridge', '4', '2017-07-19 21:16:19', 14.72, 96);
insert into event (id, provider_user_id, category_id, title, description, tags, age_from, age_to, latitude, longtitude, postal_code, street, street_number, date_time, ticket_price, available_tickets) values (20, 180, 5, 'Memphis Belle', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula', 7, 14, 38.029091, 23.801438, '57013', 'Green Ridge', '841', '2017-07-22 06:38:47', 29.94, 79);
