insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (5, 'Kozey, Crist and Romaguera', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 638792145, 0, 'Roy', 'Dykins', '891 86', 'Chive', '8642', '2084003746', 'https://robohash.org/eaqueminimapossimus.bmp?size=128x128&set=set1', '2018-06-08', '2017-06-06');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (10, 'Welch, Russel and Hudson', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.', 638792146, 1, 'Margery', 'Ronald', '57013', 'Melrose', '7', '4696050591', 'https://robohash.org/eosametautem.bmp?size=128x128&set=set1', '2019-02-15', '2017-08-23');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (15, 'Kunze Group', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 638792147, 0, 'Beltran', 'Kield', '57013', 'Fairfield', '0', '8894875783', 'https://robohash.org/eaqueremnatus.bmp?size=128x128&set=set1', '2018-08-29', '2017-05-01');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (20, 'Bogisich and Sons', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 638792148, 0, 'Gerald', 'Forgie', '57013', 'Homewood', '915', '8233297437', 'https://robohash.org/velitrepellatiure.png?size=128x128&set=set1', '2018-05-10', '2017-09-20');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (25, 'Kunde, Borer and Mosciski', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 638792149, 1, 'Newton', 'Ottosen', '788 32', 'Fair Oaks', '51', '4918515668', 'https://robohash.org/autautemomnis.bmp?size=128x128&set=set1', '2018-09-17', '2017-05-24');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (30, 'Nienow LLC', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 638792150, 0, 'Keary', 'Dowty', '57013', 'Butternut', '133', '3038610604', 'https://robohash.org/suntidoptio.jpg?size=128x128&set=set1', '2018-08-04', '2017-06-22');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (35, 'Rau-Tillman', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 638792151, 0, 'Lothaire', 'Polk', '57013', 'Golf Course', '38272', '9767083906', 'https://robohash.org/etetquasi.bmp?size=128x128&set=set1', '2018-05-29', '2017-10-27');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (40, 'Pfannerstill-Haag', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 638792152, 0, 'Olav', 'Dorcey', '57013', 'Homewood', '94142', '1998233557', 'https://robohash.org/quidoloresnam.png?size=128x128&set=set1', '2018-05-09', '2017-08-27');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (45, 'Strosin-Larson', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 638792153, 0, 'Dore', 'Methingam', '05007', 'Waywood', '8', '3302453529', 'https://robohash.org/maioreslaboriosamnisi.png?size=128x128&set=set1', '2018-07-16', '2017-04-11');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (50, 'Johnston, Sawayn and Hessel', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 638792154, 0, 'Katti', 'Threadgold', 'L-6380', 'Pepper Wood', '153', '3258733786', 'https://robohash.org/etquiacumque.bmp?size=128x128&set=set1', '2018-05-24', '2017-03-08');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (55, 'Wiza-Towne', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 638792155, 0, 'Dyan', 'Ruscoe', '96980', 'Eagle Crest', '922', '4258697263', 'https://robohash.org/voluptasautempossimus.bmp?size=128x128&set=set1', '2018-05-11', '2017-08-31');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (60, 'Wisozk and Sons', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 638792156, 0, 'Shel', 'Mattioni', '57013', 'Gulseth', '28', '5013410453', 'https://robohash.org/minusblanditiiscum.png?size=128x128&set=set1', '2018-11-03', '2017-07-15');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (65, 'Kling LLC', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 638792157, 0, 'Rudd', 'Lindman', '57013', 'Bluestem', '60', '4516345904', 'https://robohash.org/etperspiciatisut.png?size=128x128&set=set1', '2018-05-26', '2017-12-17');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (70, 'Beer and Sons', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 638792158, 1, 'Sax', 'Merwede', '3504', 'Westend', '985', '3705062172', 'https://robohash.org/adipisciidfacere.jpg?size=128x128&set=set1', '2018-06-25', '2017-07-03');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (75, 'Ziemann-Murazik', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 638792159, 1, 'Bertie', 'Gergus', '57013', 'Moulton', '2', '3581249448', 'https://robohash.org/eumametenim.bmp?size=128x128&set=set1', '2019-01-29', '2017-10-01');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (80, 'Fadel-Brekke', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 638792160, 1, 'Yorke', 'Rosenhaupt', '3515', 'Farwell', '3', '6819919864', 'https://robohash.org/corporisetsit.bmp?size=128x128&set=set1', '2018-12-08', '2017-09-08');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (85, 'Dibbert Inc', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 638792161, 0, 'Cory', 'Jewis', '57013', 'Maywood', '3', '6328710257', 'https://robohash.org/reiciendisvoluptatemsequi.png?size=128x128&set=set1', '2018-03-02', '2017-03-29');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (90, 'Johnson LLC', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.', 638792162, 1, 'Adamo', 'Rickerby', '57013', 'Center', '7', '5836591762', 'https://robohash.org/autipsumest.jpg?size=128x128&set=set1', '2018-09-16', '2018-02-09');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (95, 'Lakin Group', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 638792163, 1, 'Swen', 'Ivanitsa', '621 90', 'Harbort', '652', '8801381535', 'https://robohash.org/faciliscumqueanimi.png?size=128x128&set=set1', '2018-04-05', '2017-05-01');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (100, 'Abbott, Kassulke and Prohaska', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 638792164, 1, 'Karla', 'Wenn', '6306', 'Stoughton', '69', '9635776117', 'https://robohash.org/consecteturminimarerum.jpg?size=128x128&set=set1', '2018-10-28', '2017-04-22');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (105, 'Tillman-Stoltenberg', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 638792165, 1, 'Norrie', 'Ebbetts', '57013', 'Boyd', '318', '3452785183', 'https://robohash.org/debitismaximeeligendi.bmp?size=128x128&set=set1', '2018-06-28', '2018-02-10');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (110, 'Fritsch and Sons', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 638792166, 0, 'Ema', 'Cranney', '397641', 'Nelson', '70841', '4924520087', 'https://robohash.org/sitexercitationemvero.bmp?size=128x128&set=set1', '2018-08-02', '2017-07-07');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (115, 'Mertz-Waters', 'Fusce consequat. Nulla nisl. Nunc nisl.', 638792167, 0, 'Weber', 'Leadbitter', '366602', 'Northfield', '8080', '4174883216', 'https://robohash.org/similiquenonmagnam.jpg?size=128x128&set=set1', '2018-09-20', '2017-05-12');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (120, 'VonRueden, Wehner and Collins', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 638792168, 0, 'Elnora', 'Downey', '2409', 'Village', '79', '9455369719', 'https://robohash.org/culpaeosvoluptatibus.bmp?size=128x128&set=set1', '2018-11-05', '2017-10-24');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (125, 'Lockman-Hand', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 638792169, 1, 'Royall', 'Grazier', '57013', 'Forster', '655', '9929203769', 'https://robohash.org/laboriosamdeseruntmodi.bmp?size=128x128&set=set1', '2018-11-15', '2017-06-15');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (130, 'Harber-Dickens', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 638792170, 0, 'Banky', 'Biasioni', '57013', 'Sugar', '5342', '5718663254', 'https://robohash.org/dictateneturfugiat.png?size=128x128&set=set1', '2018-09-12', '2017-07-24');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (135, 'Jerde Group', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 638792171, 1, 'Corri', 'Shepard', '69794 CEDEX', '3rd', '672', '3012960295', 'https://robohash.org/etquaeratet.jpg?size=128x128&set=set1', '2018-09-08', '2017-12-20');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (140, 'Parisian Inc', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 638792172, 1, 'Junette', 'Shannon', '57013', 'Graceland', '94245', '7017189745', 'https://robohash.org/oditremeaque.bmp?size=128x128&set=set1', '2019-02-05', '2017-10-29');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (145, 'Rosenbaum, Schoen and Gaylord', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 638792173, 1, 'Debera', 'McMeyler', '990-2332', 'Northland', '74156', '1099802113', 'https://robohash.org/occaecatiquiareiciendis.bmp?size=128x128&set=set1', '2018-12-18', '2017-07-22');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (150, 'Medhurst-Hintz', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 638792174, 0, 'Chevalier', 'Crigin', '569 44', 'Spenser', '9090', '8898089378', 'https://robohash.org/nonrerumvoluptatem.jpg?size=128x128&set=set1', '2018-09-15', '2018-01-18');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (155, 'Pfannerstill, Wilkinson and Welch', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 638792175, 0, 'Gregorius', 'Sirrell', '57013', 'Hollow Ridge', '4083', '4199331028', 'https://robohash.org/rationenemonon.bmp?size=128x128&set=set1', '2018-03-07', '2017-12-01');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (160, 'Howe-Bartell', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 638792176, 1, 'Antonetta', 'Fidell', '2301', 'Cottonwood', '590', '1056805317', 'https://robohash.org/autemitaqueiure.bmp?size=128x128&set=set1', '2019-01-10', '2018-02-10');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (165, 'Koepp, Hand and Macejkovic', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 638792177, 0, 'Carlie', 'Stenet', '348 02', 'Donald', '91', '7198941580', 'https://robohash.org/dictanonin.bmp?size=128x128&set=set1', '2018-09-22', '2017-09-08');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (170, 'Jones and Sons', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 638792178, 1, 'Margit', 'Orpwood', '57013', 'Cottonwood', '87', '2927644617', 'https://robohash.org/consequuntureumexpedita.bmp?size=128x128&set=set1', '2018-06-28', '2017-09-16');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (175, 'Rempel-McClure', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.', 638792179, 1, 'Arabella', 'McCraine', '57013', 'Sundown', '67', '4511101025', 'https://robohash.org/autsolutarerum.bmp?size=128x128&set=set1', '2018-08-21', '2018-02-15');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (180, 'Beatty LLC', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 638792180, 1, 'Curtice', 'Frankel', '57013', 'Duke', '271', '5804036587', 'https://robohash.org/quasvoluptatemeos.png?size=128x128&set=set1', '2018-09-08', '2017-03-25');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (185, 'Bernhard LLC', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 638792181, 0, 'Ethel', 'Yule', '57013', 'West', '8992', '9382284449', 'https://robohash.org/quaeratquisequi.jpg?size=128x128&set=set1', '2018-12-02', '2017-06-23');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (190, 'Nitzsche LLC', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 638792182, 1, 'Darell', 'Bohin', '57013', 'Gulseth', '66', '2848884205', 'https://robohash.org/etcommodiad.jpg?size=128x128&set=set1', '2018-05-11', '2018-01-07');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (195, 'Kuvalis-Hartmann', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 638792183, 1, 'Cris', 'Buttress', '57013', 'Mccormick', '61220', '8313365381', 'https://robohash.org/fugaetquaerat.png?size=128x128&set=set1', '2019-01-02', '2018-01-05');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (200, 'Barrows-Hegmann', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 638792184, 1, 'Correy', 'Panks', '46-034', 'Holmberg', '043', '2524336808', 'https://robohash.org/nequevoluptatumnemo.bmp?size=128x128&set=set1', '2018-03-13', '2017-12-14');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (205, 'Hickle Inc', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 638792185, 0, 'Stefa', 'Slatford', '57013', 'Lukken', '3', '9626333383', 'https://robohash.org/idipsumin.jpg?size=128x128&set=set1', '2018-04-14', '2017-03-20');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (210, 'Runte, Bins and Marks', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 638792186, 1, 'Sheryl', 'Lum', '57013', 'Delaware', '77707', '6135122640', 'https://robohash.org/cumquenisieveniet.jpg?size=128x128&set=set1', '2018-04-13', '2017-09-25');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (215, 'Parisian-Zemlak', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 638792187, 0, 'Shae', 'Twiggs', '21140', 'Norway Maple', '25', '4215948599', 'https://robohash.org/atquiin.png?size=128x128&set=set1', '2018-07-30', '2017-09-19');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (220, 'Purdy and Sons', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 638792188, 1, 'Darcie', 'Bowstead', '57013', 'Bay', '41', '1465557283', 'https://robohash.org/voluptatumaliassapiente.png?size=128x128&set=set1', '2018-07-22', '2017-06-19');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (225, 'Gerlach Inc', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 638792189, 1, 'Brynn', 'Sarath', '57013', 'Warner', '50299', '1413900854', 'https://robohash.org/mollitiaadipiscireprehenderit.jpg?size=128x128&set=set1', '2018-07-25', '2017-03-31');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (230, 'Miller, Will and Berge', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 638792190, 0, 'Bent', 'Drowsfield', '57013', 'Anderson', '1035', '5594292307', 'https://robohash.org/iureoptiovitae.png?size=128x128&set=set1', '2018-05-30', '2017-05-04');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (235, 'Gislason-Lind', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 638792191, 0, 'Siegfried', 'Annandale', '57013', 'Emmet', '04172', '4271057643', 'https://robohash.org/maioreslaboreaspernatur.jpg?size=128x128&set=set1', '2018-03-14', '2017-11-05');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (240, 'Lesch-Emard', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 638792192, 1, 'Cori', 'Border', '57013', 'Mifflin', '476', '3668505133', 'https://robohash.org/invelitexpedita.png?size=128x128&set=set1', '2018-10-02', '2017-07-13');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (245, 'Stehr Group', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 638792193, 0, 'Milly', 'Cream', '4950-102', 'Anzinger', '991', '7654580454', 'https://robohash.org/accusamustotammolestiae.png?size=128x128&set=set1', '2018-09-27', '2017-09-12');
insert into provider (user_id, company_name, Description, AFM, is_approved, name, surname, postal_code, street, street_number, phone, photo_link, subscription_expiry_date, registration_date) values (250, 'Senger-Rempel', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 638792194, 1, 'Norby', 'Lerohan', '11205', 'Chinook', '198', '4451248014', 'https://robohash.org/quisoptiohic.png?size=128x128&set=set1', '2018-12-01', '2017-05-14');
